name: Automated Tests

on: pull_request

concurrency:
  group: tests-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  vitest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - version: 20
        os:
          - ubuntu-latest
          - windows-latest

    name: 'Vitest Node-${{ matrix.node.version }}, ${{ matrix.os }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node.version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Vitest
        run: pnpm test:run
